package com.example.polyusigwebsite.entity;

public enum AuditAction {
    REGISTER,
    LOGIN,
    OAUTH_LOGIN,
    APPROVE_MEMBER,
    REJECT_MEMBER,
    UPDATE_ROLE,
    UPLOAD_RESOURCE,
    DOWNLOAD_RESOURCE,
    DELETE_RESOURCE,
    UPDATE_RESOURCE,
    CREATE_POST,
    UPDATE_POST,
    DELETE_POST,
    SUBMIT_JOIN_APPLICATION,
    WITHDRAW_JOIN_APPLICATION,
    APPROVE_JOIN_APPLICATION,
    REJECT_JOIN_APPLICATION,
    CREATE_INTEREST_GROUP,
    UPDATE_INTEREST_GROUP,
    DELETE_INTEREST_GROUP
}
